Repository panjf2000/gnet, pull requests merged in 2024-11, with the labels that each got.

#646 feat: support configurable I/O chunk to drain at a time in edge-triggered mode
  client_test.go
  client_unix.go
  connection_windows.go
  eventloop_unix.go
  gnet.go
  gnet_test.go
  options.go
Labels: enhancement, optimization, new feature

#649 bug: fix Conn.Next not safe (#648)
  connection_unix.go
  connection_windows.go
Labels: bug, pending merged

#652 test: add test for SO_BINDTODEVICE with TCP
  client_test.go
  os_unix_test.go
  os_windows_test.go
Labels: chores, OS-Linux

#654 opt: optimize Conn.Next and Conn.Peek
  client_test.go
  connection_unix.go
  connection_windows.go
  eventloop_windows.go
  gnet_test.go
Labels: enhancement, optimization

#656 chore: rename some parameters
  client_unix.go
  client_windows.go
  connection_unix.go
  connection_windows.go
  engine_unix.go
  engine_windows.go
  eventloop_unix.go
  eventloop_windows.go
  gnet.go
  internal/netpoll/poller_epoll_default.go
  internal/netpoll/poller_epoll_ultimate.go
  internal/netpoll/poller_kqueue_default.go
  internal/netpoll/poller_kqueue_ultimate.go
  internal/queue/queue.go
  pkg/logging/logger.go
  pkg/pool/goroutine/goroutine.go
Labels: chores

#657 opt: use worker pool for asynchronous tasks on Windows
  connection_windows.go
  gnet.go
Labels: enhancement, optimization, OS-Windows, performance

#658 patch: v2.6.1
  client_test.go
  client_unix.go
  client_windows.go
  connection_unix.go
  connection_windows.go
  engine_unix.go
  engine_windows.go
  eventloop_unix.go
  eventloop_windows.go
  gnet.go
  gnet_test.go
  internal/netpoll/poller_epoll_default.go
  internal/netpoll/poller_epoll_ultimate.go
  internal/netpoll/poller_kqueue_default.go
  internal/netpoll/poller_kqueue_ultimate.go
  internal/queue/queue.go
  pkg/logging/logger.go
  pkg/pool/goroutine/goroutine.go
Labels: patch

#660 opt: eliminate the inuse eventloop.cache for idle connections
  connection_unix.go
  connection_windows.go
  eventloop_unix.go
  eventloop_windows.go
  pkg/buffer/linkedlist/linked_list_buffer.go
Labels: enhancement, optimization

#661 patch: v2.6.2
  connection_unix.go
  connection_windows.go
  eventloop_unix.go
  eventloop_windows.go
  pkg/buffer/linkedlist/linked_list_buffer.go
Labels: bug, patch
