Repository panjf2000/gnet, pull requests merged in 2024-04, with the labels that each got.

#569 bug: return 0 instead of -1 when error occurred on a write
  connection_unix.go
Labels: bug, pending merged

#572 bug: fix the EEXIST of epoll_ctl in eventloop.open
  eventloop_unix.go
Labels: bug

#574 patch: v2.4.2
  connection_unix.go
  eventloop_unix.go
Labels: bug, patch

#578 feat: support multiple network addresses binding
  README.md
  README_ZH.md
  acceptor_unix.go
  acceptor_windows.go
  client_test.go
  client_unix.go
  client_windows.go
  connection_unix.go
  connection_windows.go
  engine_unix.go
  engine_windows.go
  eventloop_unix.go
  gnet.go
  gnet_test.go
  internal/socket/fd_unix.go
  listener_unix.go
  listener_windows.go
  os_unix_test.go
  pkg/errors/errors.go
  reactor_epoll_default.go
  reactor_kqueue_default.go
Labels: new feature, docs

#580 opt: only enable SO_REUSEPORT on Linux and FreeBSD
  gnet.go
  internal/socket/sockopts_freebsd.go
  internal/socket/sockopts_posix.go
  internal/socket/sockopts_unix1.go
Labels: enhancement, optimization

#583 opt: don't disable SO_REUSEPORT on DragonFlyBSD
  gnet.go
Labels: enhancement, optimization

#584 opt: disable SO_REUSEPORT on Unix domain sockets
  gnet.go
  options.go
Labels: enhancement

#585 opt: enable ET mode on listener event-loop by default
  acceptor_unix.go
  engine_unix.go
  eventloop_unix.go
Labels: enhancement, optimization, performance

#586 opt: refine the code of I/O handlers
  acceptor_bsd.go
  acceptor_linux.go
  acceptor_unix.go
  connection_bsd.go
  connection_linux.go
  connection_unix.go
  engine_unix.go
  eventloop_unix.go
  internal/netpoll/defs_poller.go
  internal/netpoll/defs_poller_epoll.go
  internal/netpoll/defs_poller_kqueue.go
  internal/netpoll/poller_epoll_default.go
  internal/netpoll/poller_epoll_ultimate.go
  reactor_epoll_default.go
  reactor_kqueue_default.go
Labels: enhancement, optimization

#587 opt: reduce duplicate code of I/O processing
  acceptor_unix.go
  connection_bsd.go
  connection_linux.go
  eventloop_unix.go
  eventloop_windows.go
  gnet_test.go
  reactor_epoll_default.go
  reactor_epoll_ultimate.go
  reactor_kqueue_default.go
  reactor_kqueue_ultimate.go
Labels: enhancement, pending merged, optimization

#588 minor: v2.5.0
  README.md
  README_ZH.md
  acceptor_unix.go
  acceptor_windows.go
  client_test.go
  client_unix.go
  client_windows.go
  connection_bsd.go
  connection_linux.go
  connection_unix.go
  connection_windows.go
  engine_unix.go
  engine_windows.go
  eventloop_unix.go
  eventloop_windows.go
  gnet.go
  gnet_test.go
  internal/netpoll/defs_poller.go
  internal/netpoll/defs_poller_epoll.go
  internal/netpoll/defs_poller_kqueue.go
  internal/netpoll/poll_data_bsd.go
  internal/netpoll/poll_data_linux.go
  internal/netpoll/poller_epoll_default.go
  internal/netpoll/poller_epoll_ultimate.go
  internal/netpoll/poller_kqueue_default.go
  internal/netpoll/poller_kqueue_ultimate.go
  internal/socket/fd_unix.go
  internal/socket/sockopts_freebsd.go
  internal/socket/sockopts_posix.go
  internal/socket/sockopts_unix1.go
  listener_unix.go
  listener_windows.go
  options.go
  os_unix_test.go
  pkg/buffer/elastic/elastic_buffer_test.go
  pkg/buffer/elastic/elastic_ring_list_buffer.go
  pkg/buffer/linkedlist/linked_list_buffer.go
  pkg/buffer/linkedlist/llbuffer_test.go
  pkg/errors/errors.go
  reactor_default_bsd.go
  reactor_default_linux.go
  reactor_epoll_default.go
  reactor_epoll_ultimate.go
  reactor_kqueue_default.go
  reactor_kqueue_ultimate.go
Labels: enhancement, optimization, new feature, docs, minor, OS-Linux, OS-Darwin, OS-Windows, OS-FreeBSD, OS-OpenBSD, OS-NetBSD, OS-Dragonfly

#590 opt: reduce duplicate code for I/O reactors
  reactor_default.go
  reactor_kqueue_default.go
  reactor_kqueue_ultimate.go
  reactor_ultimate.go
Labels: enhancement, optimization
